### ISSUE TITLE
Duplicate set before returning in EpochMap.removeSet

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/JavaSpiNNaker#1028]
I've been wondering whether this set should be copied so that the references become strong ones.

_Originally posted by @dkfellows in https://github.com/SpiNNakerManchester/JavaSpiNNaker/pull/992#discussion_r1314632101_

**NB:** Duplicate by using `WeakHashMap.forEach` to avoid ConcurrentModificationException, which means unwrapping things internally.

**Comment by dkfellows** [comment]
The difficulty is, of course, that the wait set can be asynchronously modified and we can't stop it from happening or even really synchronize to delay it. Tricky stuff!

**Comment by rowleya** [comment]
It is suggested here that the GC shouldn't cause a ConcurrentModificationException:
https://stackoverflow.com/questions/2861410/weakhashmap-iteration-and-garbage-collection
