### ISSUE TITLE
// force line wrap

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#103]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
	private final Map<BMPCoords, ConnectionSelector<BMPConnection>>
		// force line wrap
		bmpSelectors = new HashMap<>();
============================

What do you see that is wrong?
i find this very disconnecting. Ive been hit by it before with other modules, but id rather have a better solution than this

What do you think it should do instead?
can it be done as follows:
	private final Map<BMPCoords, ConnectionSelector<BMPConnection>>
		bmpSelectors = new HashMap<>(); // force line wrap

What version of our software are you using?
master
-------------------------------------------

**Comment by rowleya** [comment]
Hmm, I agree that this uglifies the code for a formatting issue.  My eclipse formatter does this with the line:
```
private final Map<BMPCoords, ConnectionSelector> bmpSelectors =
            new HashMap<>();
```
I am happy with this.  Is there something worse that eclipse does?

**Comment by rowleya** [comment]
I should add that the above is less ugly in my opinion than
```
private final Map<BMPCoords, ConnectionSelector>
// force line wrap
bmpSelectors = new HashMap<>();
```

**Comment by dkfellows** [comment]
The problem is that this:

	private final Map<BMPCoords, ConnectionSelector<BMPConnection>> bmpSelectors =
			new HashMap<>();

exceeds the maximum line length (by 2 characters). I need to figure out how to allow Eclipse to auto-wrap in other places in the line.

**Comment by rowleya** [comment]
Mine produces this:
```
private final Map<BMPCoords,
            ConnectionSelector<BMPConnection>> bmpSelectors =
                    new HashMap<>();
```

Does yours not let this happen?

**Comment by rowleya** [comment]
Here are my rules:
[JavaFormatter.xml.txt](https://github.com/SpiNNakerManchester/JavaSpiNNaker/files/2639577/JavaFormatter.xml.txt)

I must have updated them from the defaults, but admit that I don't know what I changed!  One minor change has resulted in this:
```
private final Map<BMPCoords,
            ConnectionSelector<BMPConnection>> bmpSelectors = new HashMap<>();
```

**Comment by dkfellows** [comment]
Found the setting. Obscure? You betcha!

**Comment by alan-stokes** [comment]
there's at least 1 more place i remember seeing this. might be worth doing a search for the force line thingy.

**Comment by dkfellows** [comment]
Must've fixed that in passing.
