### ISSUE TITLE
Transceiver.java ExecuteLock

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#112]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
the class def for ExecuteLock is at lines 676 to 698, the usage of said class doesnt start till 1291.
============================

What do you see that is wrong?
the executeLock is nowhere near the code that uses it

What do you think it should do instead?
either:
1. be located next to where its used
2. plonk all these extra classes at the bottom of the class, so that we're not muddying the water

I personally perfer 2. 

What version of our software are you using?
master
-------------------------------------------

**Comment by Christian-B** [comment]
I have a preference for defining inner classes at the very bottom. (except anonymous ones of course)

I would accept if it is just above or just below the ONLY place the classes is used but still ugly!

**Comment by dkfellows** [comment]
The whole locking mechanism is ugly.
