### ISSUE TITLE
using chemical gas constant

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#115]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
line 798
============================

What do you see that is wrong?
turn into a true variable, retry comes to mind. not the gas constant. 

What do you think it should do instead?
better name

What version of our software are you using?
master
-------------------------------------------

**Comment by Christian-B** [comment]
Line 798 of WHAT!

**Comment by alan-stokes** [comment]
Transceiver.java

**Comment by dkfellows** [comment]
“chemical gas constant”??? Wat.

**Comment by alan-stokes** [comment]
r 
basically 1 letter variables. retry instead of r. theres also conn/connection instead of c all over the place.

**Comment by dkfellows** [comment]
Using a single-letter variable _internally_ to a method isn't a big deal.

**Comment by alan-stokes** [comment]
readability. i reject your response and reopen

**Comment by alan-stokes** [comment]
*pulls out the drums*

**Comment by dkfellows** [comment]
FWIW, I've _seen_ what actually happens when people put in style rules to prohibit local variable names like `i` and so on…

Programmers mostly just double the letter up! Yes, `ii` is the new `i`. 🤦‍♂️

**Comment by alan-stokes** [comment]
Programmers mostly just double the letter up! Yes, ii is the new i

WTF! are you telling me youd do that! coz if so, my respect for ya just dropped a notch. lol.  i, or ii, or iii or any number of i's is not a valid variable name.

**Comment by rowleya** [comment]
You could add a rule that requires that every variable is made up of dictionary words!

(For the avoidance of doubt, the above is not expected to be taken seriously).

**Comment by Christian-B** [comment]
I can understand the python rule that disallows the single letter variable names l and O as they looks like the numbers 1 and 0.

But other single variable names are a question of taste.

For i ... is perfectly fine. 

We also have x, y, p all over the place and that is fine and should not be otherwise.

The c and r here are more open to taste,
