### ISSUE TITLE
missing param

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#116]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
Transceiver.java line 477
============================

What do you see that is wrong?
connections not used

What do you think it should do instead?
use connections as second arg. 

What version of our software are you using?
master
-------------------------------------------

**Comment by dkfellows** [comment]
Pretty sure I fixed this on some branch already, but not yet on master.
