### ISSUE TITLE
Transceiver.java 932 and 795

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#118]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
check connection is only used by discoverScampConnections. The int retries thus can be removed and the magicNumber STANDARD_RETRIES_NO could be pushed inside instead
============================

What do you see that is wrong?
extra utilisation of magic number

What do you think it should do instead?
psuh STANDARD_RETRIES_NO into check_connection

What version of our software are you using?
master
-------------------------------------------

**Comment by Christian-B** [comment]
GIGO Python is the same.

**Comment by alan-stokes** [comment]
so lets repeat the steps of issue https://github.com/SpiNNakerManchester/JavaSpiNNaker/issues/117
so to rowley we go

**Comment by Christian-B** [comment]
Fixed in both Java and Python
