### ISSUE TITLE
getSystemVariable

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#120]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
getSystemVariable can return a null, but code depending on it will automaitcally cast it to byte[]. so blow up
============================

What do you see that is wrong?
the default of the getSystemVariable should be a error instead of null

What do you think it should do instead?
error instead of null

What version of our software are you using?
master
-------------------------------------------

**Comment by Christian-B** [comment]
Transceiver Line 652:

Agreed this is sloppy coding.
Better to throw an UnsupportedOperationException

**Comment by dkfellows** [comment]
IllegalStateException is better.
