### ISSUE TITLE
cast for what seems no reason (Transceiver.java line 830)

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#125]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
SDPSender c = connection;
		if (c == null) {
			c = getRandomConnection(sdpSenderConnections);
		}
		c.sendSDPMessage(message);
============================

What do you see that is wrong?
likely due to now having a type control, the SDPConnection connection has a sendSDPMessage, So dont need to cast it to SDPSender

What do you think it should do instead?
remove the cast,

What version of our software are you using?
master
-------------------------------------------

**Comment by dkfellows** [comment]
Yes, but `getRandomConnection()` isn't guaranteed to be returning an `SDPConnection`, but rather just a `SDPSender`.
