### ISSUE TITLE
DEFAULT_RETRIES

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#140]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
found in SCPRequestPipeline and SendSingleBMPCommandProcess 
============================

What do you see that is wrong?
should be common constant, to stop cloning

What do you think it should do instead?
put in constants file

What version of our software are you using?
master
-------------------------------------------

**Comment by dkfellows** [comment]
Unified the constants.
