### ISSUE TITLE
SpallocJob.java

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#149]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
keepalive is spread a lot through this class
============================

What do you see that is wrong?
keepalive vs keepAlive

What do you think it should do instead?
keepAlive

What version of our software are you using?
master
-------------------------------------------

**Comment by alan-stokes** [comment]
same for SpallocClient.java (line 250)

**Comment by dkfellows** [comment]
Don't want to fix this one.

**Comment by alan-stokes** [comment]
ill let the guru win some small victories. 😉
