### ISSUE TITLE
Strip out Slice class

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/JavaSpiNNaker#15]
uk.ac.manchester.spinnaker.io.AbstractIO

Has an inner class Slice.

Would it not be better to strip this out as a utils class and considering how often. we use slice in python.

If you agree assign to me and I will go ahead.

**Comment by dkfellows** [comment]
Seems OK to me. I tend to start by putting classes as inner classes and then migrate them out if they're more useful.
