### ISSUE TITLE
"machine", "chip_x", "chip_y", "where_is", "cabinet", "frame", "board", "x", "y", "z", "job_id"

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#154]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
"machine", "chip_x", "chip_y", "where_is", "cabinet", "frame", "board", "x", "y", "z", "job_id"
these are used loads of places
============================

What do you see that is wrong?
currently magic strings

What do you think it should do instead?
constants to link to these

What version of our software are you using?
master
-------------------------------------------

**Comment by Christian-B** [comment]
If there is even a remote chance any of these could change I would argee.

For example in database column names.

But in these cases I don't think they will ever every change.

**Comment by alan-stokes** [comment]
up to you two.

**Comment by dkfellows** [comment]
I think those are all determined by the Spalloc protocol.
