### ISSUE TITLE
WhereIs.java

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#155]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
if (o != null && o instanceof WhereIs) { (line 205)
============================

What do you see that is wrong?
o != null && is redundant

What do you think it should do instead?
go bye bye

What version of our software are you using?
master
-------------------------------------------

**Comment by dkfellows** [comment]
Already fixed for #124
