### ISSUE TITLE
JobsChangedNotification.java line 56

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#157]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
if (other == null || !(other instanceof JobsChangedNotification)) {
============================

What do you see that is wrong?
other == null || is redundant

What do you think it should do instead?
go bye bye

What version of our software are you using?
master
-------------------------------------------

**Comment by dkfellows** [comment]
Fixed for #124
