### ISSUE TITLE
Put Machine report in Machine

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/JavaSpiNNaker#16]
uk.ac.manchester.spinnaker.transceiver.Reports  does not belong in Communications.

My suggestion is to move the write machien stuff to machine and possibly leave just a wrapper to do the 
uk.ac.manchester.spinnaker.connections.model.Connection behind.

if you agree assign to me and I will strip out the Machine part.

**Comment by dkfellows** [comment]
_YES!_

**Comment by Christian-B** [comment]
done
