### ISSUE TITLE
command.java

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#160]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
	protected final void addArg(A... values) {
		for (final A value : values) {
			args.add(value);
		}
	}
(lines 54 to 58)
============================

What do you see that is wrong?
manual adding into collection

What do you think it should do instead?
	protected final void addArg(A... values) {
		Collections.addAll(args, values);
	}

What version of our software are you using?
master
-------------------------------------------

**Comment by Christian-B** [comment]
Considering that Collections.addAll does the EXACT same thing this suggestion does not make sense!

**Comment by Christian-B** [comment]
In fact Collections.addAll does extra work!

**Comment by alan-stokes** [comment]
Considering that Collections.addAll does the EXACT same thing

exactly, if its doing the same tyhing, why reengineer it. do we do math.ceil or figure it out itself. 

reduced code when theres a normal way to do it
