### ISSUE TITLE
BoardPhysicalCoordinates

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#161]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
if (o != null && o instanceof BoardPhysicalCoordinates) {
line 82
============================

What do you see that is wrong?
same about the (o != null && 

What do you think it should do instead?
go bye bye

What version of our software are you using?
master
-------------------------------------------

**Comment by alan-stokes** [comment]
from now on, leaving these for a blanket cull. no more issues will be posted about it

**Comment by dkfellows** [comment]
Fixed in #124
