### ISSUE TITLE
Constants.java in messages module

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#162]
What is the problem you see?
-
NO_MIDDLE_CHIPS_TO_CHECK never used (also never used in python, cull required)
DEFAULT_SDP_TAG is the same issue
EIEIO_DATA_HEADER_SIZE is the same
EIEIO_COMMAND_HEADER_SIZE is the same
SYSTEM_VARIABLE_BYTES is the same

What do you see that is wrong?
-
these are not ANYWHERE

What do you think it should do instead?
-
go bye bye

What version of our software are you using?
-
master

**Comment by alan-stokes** [comment]
and SHORT_SIZE

**Comment by dkfellows** [comment]
But how else will we know the size of shorts to wear?

**Comment by alan-stokes** [comment]
so it was being used by a clone?

**Comment by Christian-B** [comment]
removed python too label as fixed in 
https://github.com/SpiNNakerManchester/SpiNNMan/commit/ecc70d4472bce6664b96d08d4f56d721618ca831

**Comment by Christian-B** [comment]
added wontfix as only remaining constant not being removed

**Comment by dkfellows** [comment]
Remaining actions need not block 6.0 release
