### ISSUE TITLE
SDRAMMAlloc.java

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#163]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
SDRAMMAlloc
============================

What do you see that is wrong?
SDRAMMAlloc vs SDRAMMalloc

What do you think it should do instead?
SDRAMMalloc

What version of our software are you using?
master
-------------------------------------------

**Comment by dkfellows** [comment]
It's “`SDRAM` `Alloc`”, and I'm not sure where there's the other form.

**Comment by alan-stokes** [comment]
i retract the issue. as It seems this was my eyes playing tricks on me
