### ISSUE TITLE
MAGIC1 MAGIC2 in FloodFillDATA, END, START

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#166]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
these are cloned, move to constant place and use
============================

What do you see that is wrong?

What do you think it should do instead?

What version of our software are you using?
master
-------------------------------------------

**Comment by alan-stokes** [comment]
its also used in ApplicationStop as well

**Comment by Christian-B** [comment]
Magic1 and magic2 used as Python does nopt define what they are.

@alan-stokes please suggest names.

**Comment by rowleya** [comment]
I suspect these come out of ybug.  From looking at code, the numbers are probably "forward" and "retry", which are defined as follows:
```
    // forward[5:0] Which links should the packet be sent down
    // forward[6] If reset (fwd[6]==0), link numbers above will be treated
    //            as relative to the packet's incoming link, i.e., fwd[0]
    //            means send to the incoming link. For example. if a packet
    //            comes in on the south link, fwd[0] means send South, fwd[1]
    //            means send East, and so on counterclockwise.
    //            If set (fwd[6]==1), link numbers above will be treated as
    //            absolute, i.e., fwd[0] means send East, fwd[1] means send
    //            NorthEast, and so on counterclockwise.
    //            To send to all links except the incoming one use:
    //            forward[6:0] = 0x3e [relative and not to incoming link (0)].
    // retry[2:0] number of additional times to repeat the packet (i.e. sent
    //            this many times + 1)
    // retry[7:3] The number of usec to wait between repeated packets is
    //            wait = (8 * retry[7:3]) + 8
```

This is for Nearest Neighbour transmission, so the idea is that as a core receives a message, it forwards it on to neighbouring links as defined in the forward, so the packet propagates over the machine.  Retry is how many repeats to send (these are sent regardless of any knowledge of acceptance as packets can be dropped) and how long between sending them (using a fun fixed-point format).
