### ISSUE TITLE
SystemVariableDefinition.java

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#170]
Full path to where you find the problem:
JavaSpiNNaker\SpiNNaker-comms\src\main\java\uk\ac\manchester\spinnaker\messages\model\SystemVariableDefinition.java

What is the problem you see?
padding1,2,3,4 add comment to @Deprecated to why its deprecated (rowley advised)

What do you think it should do instead?

What version of our software are you using?

**Comment by alan-stokes** [comment]
same on C:\Users\alan\Documents\software\JavaSpiNNaker\SpiNNaker-comms\src\main\java\uk\ac\manchester\spinnaker\messages\model\CPUState.java

for CPU_STATE_12 ,13, 14

**Comment by Christian-B** [comment]
spinnaker/SpiNNMan/spinnman/model/enums/cpu_state.py

can you guarantee these will never be used?

**Comment by dkfellows** [comment]
The padding values are deprecated because they're _just padding bytes_.

**Comment by alan-stokes** [comment]
still add docs.

**Comment by dkfellows** [comment]
No.
