### ISSUE TITLE
ChipSummaryInfo.java (IDE gripe)

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#172]
Full path to where you find the problem:
C:\Users\alan\Documents\software\JavaSpiNNaker\SpiNNaker-comms\src\main\java\uk\ac\manchester\spinnaker\messages\model\ChipSummaryInfo.java

What is the problem you see?
private static final byte[] NO_ADDRESS = new byte[ADDRESS_SIZE];

What do you think it should do instead?
    @SuppressWarnings("MismatchedReadAndWriteOfArray")
    private static final byte[] NO_ADDRESS = new byte[ADDRESS_SIZE];

What version of our software are you using?
master

**Comment by dkfellows** [comment]
I don't understand this warning.

**Comment by alan-stokes** [comment]
the warning is that your building a array that you never write to. I guess the ide doesnt like arrays that are only ever read. choose what you wish with it.

**Comment by dkfellows** [comment]
Wrote it out more explicitly.
