### ISSUE TITLE
HostSendSequencedData.java line 64

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#173]
Full path to where you find the problem:
C:\Users\alan\Documents\software\JavaSpiNNaker\SpiNNaker-comms\src\main\java\uk\ac\manchester\spinnaker\messages\eieio\HostSendSequencedData.java

What is the problem you see?
	public int minPacketLength() {
		return super.minPacketLength() + 2;
	}

What do you think it should do instead?
masgic number, vs named 

What version of our software are you using?
master

**Comment by dkfellows** [comment]
Oh, a converted Sergeieio-ism…

**Comment by dkfellows** [comment]
Aaaand… in SpiNNMan it is ugly in a different way!
