### ISSUE TITLE
0b00000011

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#177]
Full path to where you find the problem:
C:\Users\alan\Documents\software\JavaSpiNNaker\SpiNNaker-comms\src\main\java\uk\ac\manchester\spinnaker\messages\bmp\ReadFPGARegister.java
C:\Users\alan\Documents\software\JavaSpiNNaker\SpiNNaker-comms\src\main\java\uk\ac\manchester\spinnaker\messages\bmp\WriteFPGARegister.java
C:\Users\alan\Documents\software\JavaSpiNNaker\SpiNNaker-comms\src\main\java\uk\ac\manchester\spinnaker\messages\eieio\EIEIODataMessage.java
C:\Users\alan\Documents\software\JavaSpiNNaker\SpiNNaker-comms\src\main\java\uk\ac\manchester\spinnaker\messages\scp\FloodFillStart.java
C:\Users\alan\Documents\software\JavaSpiNNaker\SpiNNaker-data-specification\src\main\java\uk\ac\manchester\spinnaker\data_spec\Functions.java

What is the problem you see?
these all define the same constant (albeit some with naming little differences, but some are constant names), with the same value

What do you think it should do instead?
its likely some (im not silly enough to assume all can) can be merged into one constant located in constants.java

What version of our software are you using?
master

**Comment by dkfellows** [comment]
No. They don't represent the same thing.

**Comment by alan-stokes** [comment]
They do in ReadFPGARegister and WriteFPGARegister for starters. So that one at least needs to be merged

**Comment by dkfellows** [comment]
One represents the register mask for a read and the other for a write. _Those are not required to be the same._ Yes, this is all shonky bit bashing, but no, I **refuse** to merge them.

**Comment by alan-stokes** [comment]
ok, i will relent. But rename them so that they dont have the saem name. Such that we dont get motivated to assume they cant be merged
