### ISSUE TITLE
Constants.java

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#182]
Full path to where you find the problem:
many places:
spalloc.JobConstants, io.Constants, utils.UnitConstants, messages.Constants, 

What is the problem you see?
io.Constants and messages.Constants dont match naming conventions of the module ish name before it. Allowing easier tracking

What do you think it should do instead?
MessageConstants, IOConstants

What version of our software are you using?
master

**Comment by dkfellows** [comment]
`…io.Constants` deleted anyway, and there's no general rule.

Track using the fully qualified name.
