### ISSUE TITLE
ChipMemoryIO.java

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#184]
Full path to where you find the problem:
C:\Users\alan\Documents\software\JavaSpiNNaker\SpiNNaker-comms\src\main\java\uk\ac\manchester\spinnaker\io\ChipMemoryIO.java

What is the problem you see?
		Map<ChipLocation, ChipMemoryIO> map = existing.get(transceiver);
		if (map == null) {
			map = new HashMap<>();
			existing.put(transceiver, map);
		}

What do you think it should do instead?
Map<ChipLocation, ChipMemoryIO> map = existing.computeIfAbsent(transceiver, k -> new HashMap<>());

What version of our software are you using?
master

**Comment by dkfellows** [comment]
Already done. And immediately below it too.
