### ISSUE TITLE
lambda

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#188]
Full path to where you find the problem:
C:\Users\alan\Documents\software\JavaSpiNNaker\SpiNNaker-comms\src\main\java\uk\ac\manchester\spinnaker\transceiver\processes\SendSingleBMPCommandProcess.java

What is the problem you see?
toRemove.stream().forEach(seq -> requests.remove(seq));

What do you think it should do instead?
toRemove.stream().forEach(requests::remove);

What version of our software are you using?
master

**Comment by dkfellows** [comment]
Already gone
