### ISSUE TITLE
redundant constructor

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#192]
Full path to where you find the problem:
C:\Users\alan\Documents\software\JavaSpiNNaker\SpiNNaker-comms\src\main\java\uk\ac\manchester\spinnaker\connections\SCPConnection.java

What is the problem you see?
	/**
	 * Create a connection to a particular instance of SCAMP.
	 *
	 * @param remoteHost
	 *            The remote host to send messages to.
	 * @param remotePort
	 *            The optional remote port number to send messages to. If
	 *            {@code null}, the default remote port is used.
	 * @throws IOException
	 *             If anything goes wrong with socket setup.
	 */
	public SCPConnection(InetAddress remoteHost, Integer remotePort)
			throws IOException {
		this(DEFAULT_CHIP, null, null, remoteHost, remotePort);
	}

What do you think it should do instead?
never used in the tools

What version of our software are you using?
master

**Comment by dkfellows** [comment]
Slaughtered. Forgot to commit it separately.
