### ISSUE TITLE
default chip 

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#193]
Full path to where you find the problem:
-
`SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/SCPConnection.java`

What is the problem you see?
-
the `DEFAULT_CHIP` is risky for causing multiple connections to point at the same boot. forcing the app to set it will remove this risk. On most of the use cases, we already set the chip. only place that seems to not use it is line 414 in txrx which is:
```java
		if (scampConnections.isEmpty()) {
			connections.add(new SCPConnection(host));
		}
```
in the consturctor

What do you think it should do instead?
-
See above

What version of our software are you using?
-
`master`

See also:
* SpiNNakerManchester/SpiNNMan#148

**Comment by dkfellows** [comment]
I'll figure out what to do about this once I see how you guys fix SpiNNMan…

**Comment by dkfellows** [comment]
Using the `getTransceiver()` method of the new spalloc client job class (in comms) results in a transceiver with separate connections to each board (and no BMP access at all).

**Comment by dkfellows** [comment]
If you do it all manually, you need to get things right. Current preferred mode of operation is you ask spalloc (old or new) to give you a transceiver; it knows how. Only doesn't really apply when you use local boards, and then you can either use the defaults (fine for a single board) or Get It Right&trade;.
