### ISSUE TITLE
camel case

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#200]
Full path to where you find the problem:
C:\Users\alan\Documents\software\JavaSpiNNaker\SpiNNaker-utils\src\main\java\uk\ac\manchester\spinnaker\utils\RawConfigParser.java

What is the problem you see?
public Integer getint(String section, String option) {
public Boolean getboolean(String section, String option) {

What do you think it should do instead?
public Integer getInt(String section, String option) {
public Boolean getBoolean(String section, String option) {

What version of our software are you using?
master

**Comment by dkfellows** [comment]
Was modelling what we had in Python. It sucks there too!
