### ISSUE TITLE
redundant methods in abstractIO.java

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#205]
Full path to where you find the problem:
-
`SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/io/AbstractIO.java`

What is the problem you see?
-
the ide thinks `asOutputStream` and `asInputStream` are not used......

What do you think it should do instead?
-
consider going bye bye

What version of our software are you using?
-
`more-fixing`

**Comment by dkfellows** [comment]
IDE is correct, but I decline to fix this as I don't what we will do with this package in the future.

**Comment by alan-stokes** [comment]
k.
