### ISSUE TITLE
defaultChip vs BootChip

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#206]
Full path to where you find the problem:
starts in SCPRequest (C:\Users\alan\Documents\software\JavaSpiNNaker\SpiNNaker-comms\src\main\java\uk\ac\manchester\spinnaker\messages\scp\SCPRequest.java)

What is the problem you see?
	public static final CoreLocation DEFAULT_MONITOR_CORE =
			new CoreLocation(DEFAULT_DEST_X, DEFAULT_DEST_Y, 0);
    /**
	 * The pseudo-location of the default chip.
	 */
	public static final ChipLocation DEFAULT_CHIP =
			DEFAULT_MONITOR_CORE.asChipLocation();

What do you think it should do instead?
the 255 255 is actually the boot chip, not the default chip. took a good while with @lplana and @rowleya to get to that logic, but basically, default_chip is a misnomer

What version of our software are you using?
more-fixing

**Comment by dkfellows** [comment]
I see what you're saying, but I don't know what to do about it. 😄

**Comment by alan-stokes** [comment]
I think its a renaming task.
