### ISSUE TITLE
TestTransceiver fails in windows

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/JavaSpiNNaker#216]
Full path to where you find the problem:
uk.ac.manchester.spinnaker.transceiver.TestTransceiver (in tests of course)

What is the problem you see?
java.net.SocketException: Network is unreachable: connect
	at uk.ac.manchester.spinnaker.transceiver.TestTransceiver.testSetWatchdog(TestTransceiver.java:191)

What do you think it should do instead?
possible check for window or skip on faik

What version of our software are you using?
extractor2

**Comment by dkfellows** [comment]
That one is supposed to be run with a mock against an unreachable host. (It also works for me when I re-enable the test.) I wonder what's going wrong.

**Comment by dkfellows** [comment]
Looks like the same root cause as #215, and I suspect the problem is an ISP being “helpful” because “all the world ever runs is webpages”.
