### ISSUE TITLE
Get rid of the max core ID constructor parameter  in python

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#220]
Full path to where you find the problem:
see https://github.com/SpiNNakerManchester/JavaSpiNNaker/pull/219

What is the problem you see?

What do you think it should do instead?

What version of our software are you using?

**Comment by Christian-B** [comment]
This have nothing to do with Java!

Why is this issue here?

**Comment by alan-stokes** [comment]
(swear)

**Comment by alan-stokes** [comment]
https://github.com/SpiNNakerManchester/SpiNNMachine/issues/92
