### ISSUE TITLE
EIEIODataMessage static min_packet_length??????

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/JavaSpiNNaker#24]
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/blob/master/spinn_front_end_common/interface/buffer_management/buffer_manager.py

Lines 40-41

EIEIODataMessage.min_packet_length(
    eieio_type=EIEIOType.KEY_32_BIT, is_timestamp=True)

What is the Java equivellent?

**Comment by dkfellows** [comment]
The Java equivalent is `6`, which is 2 bytes of generic EIEIO header, 4 bytes of key (for 32 bits) and 0 bytes of payload (as it is `KEY_32_BIT`, not `KEY_PAYLOAD_32_BIT`).

I guess we could calculate it.

**Comment by rowleya** [comment]
If is_timestamp is True, I think you get an extra 4 bytes for the timestamp itself

**Comment by dkfellows** [comment]
No; it just does this internally:

        header_size = EIEIODataHeader.get_header_size(
            eieio_type, is_prefix, is_payload_base | is_timestamp)
        return header_size + eieio_type.payload_bytes

**Comment by rowleya** [comment]
Ah yes, 6 is correct, but it is 2 for the generic header and 4 for the timestamp, which is a payload, even though there isn't a payload.  For the record, I think the protocol is pretty ugly.

**Comment by dkfellows** [comment]
> For the record, I think the protocol is pretty ugly.

Quoted For Truth.

**Comment by dkfellows** [comment]
For double fun, where does the mystery `280` in the buffer manager implementation come from?

**Comment by rowleya** [comment]
I suspect this is the true maximum size of the data in a UDP message sent to SpiNNaker (=256 bytes from the SCP data field + 3 x 4 bytes from unused SCP arguments + 2 bytes from the cmd header + 2 bytes from the sequence number + 8 bytes from the rest of the SDP header).  There *might* be an issue in using that additional 8 bytes from the SDP header however as the packets will be forwarded on within SpiNNaker as SDP packets, so 280 might be a bit too big and 272 might be the more accurate number.

**Comment by Christian-B** [comment]
280 question moved to: https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/343

**Comment by Christian-B** [comment]
Hard coded 6 into the magic number in BufferManager. we can create a method if we really need it.
