### ISSUE TITLE
Downloader doesn't timeout even though a core has stopped responding

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/JavaSpiNNaker#316]
The downloader doesn't timeout even though the core on SpiNNaker has died.  The core died with an RTE (see SpiNNakerManchester/SpiNNFrontEndCommon#796).

Zip attached containing jspin.log and stack traces from jstack.

[error_files.zip](https://github.com/SpiNNakerManchester/JavaSpiNNaker/files/6377263/error_files.zip)

**Comment by dkfellows** [comment]
See #453
