### ISSUE TITLE
Keep job details beyond the end of the job

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/JavaSpiNNaker#366]
For debugging, it could be useful to keep job details beyond a job being "destroyed".  This could then let users "see" the boards that were used in a job in the past.  This might have an expiry date e.g. 1 month.

**Comment by dkfellows** [comment]
Job details are kept (first in operational store, and then gradually migrated to longer term append-only storage in a separate database). But how should they be displayed to users? Note that some users (e.g., key service users) may end up having _very_ large numbers of old jobs. (The destroyed jobs should be listable right now — excluding the archived jobs — _except_ I've literally not written the UI to do it. The REST API supports paged access.)

**Comment by rowleya** [comment]
If this only supports jobs in the operational store, that would be fine as it is more likely that it would be used to find out what went wrong on something reasonably recent (and with the knowledge that the jobs will disappear eventually, debugging information can be extracted early and logged elsewhere if the issue isn't to be fixed immediately).

**Comment by dkfellows** [comment]
The tombstoning copies old jobs (currently configured to be ones 14 days dead) to a database that I'm treating as if it is append-only.

**Comment by dkfellows** [comment]
What I don't currently keep is the list of boards (by id most likely) that were allocated to the job...

**Comment by rowleya** [comment]
I guess it is possible to calculate that if you know where it starts and how many boards, but it would be nice to have anyway.

**Comment by dkfellows** [comment]
We should now keep the allocation records beyond the end of the job; they'll also get migrated to the historical data DB when the job gets moved.

Keeping this issue open: not sure that that's all the information we want to keep.
