### ISSUE TITLE
Spalloc max_dead_boards vs n_boards

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/JavaSpiNNaker#410]
In the current spalloc if you request 3 boards but change max_dead_boards to 1 it will return a machine with 2 working boards.

There is a defensible view that well you asked for 3 boards and said one of those three could be dead so you got what you asked for.

This is not an issue with the current code as max_dead_boards is always 0 unless you change code.

This issue is more about the new spalloc which I have been informed is more likely to have holes.
My understand is that is so it can allocate a big machine even if there are several small ones scattered around, rather than having to wait for a whole free block.

What is critical is that the client asks for n_boards using the default settings for any other values (except of course spalloc_machine, spalloc_port, spalloc_user) that they get n working boards.

**Comment by dkfellows** [comment]
Cross-checking: if you ask for just a number of boards, you'll get that number of boards (as a connected group) and the max dead boards will be ignored (the info simply isn't passed along). The max number of dead boards is only used when you ask for a rectangle.

**Comment by rowleya** [comment]
That is fine; max dead boards is a maximum any way, so it is just to ensure you get the number you asked for.

**Comment by dkfellows** [comment]
I don't plan to do any changes to satisfy this issue. I've no objection to someone reopening the issue if they have a better idea.
