### ISSUE TITLE
Quota API

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/JavaSpiNNaker#414]
Related to #413 it would be useful to have an API with which an external script could interact to synchronize quotas between HBP and SpiNNaker allocations.

Things this might need to do:
 - Add a group and allocate users to the group with a group quota.
 - Read the group quotas remaining.

**Comment by dkfellows** [comment]
Putting a REST API in is easy enough (provided we have a good definition of who can do what operations) subject to the issues relating to the naming of things.

**Comment by dkfellows** [comment]
This is the main part left undecided. I simply don't know what APIs elsewhere we would be interacting with. But the basic units of accounting would be board-seconds; that's totally what it is easy for us to work with.

**Comment by dkfellows** [comment]
See:
* #929

**Comment by rowleya** [comment]
This has been done otherwise so closing.
