### ISSUE TITLE
Enhancement: Allow spalloc server to allocate a group of boards starting at a specific coordinate

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/JavaSpiNNaker#432]
It would be useful to be able to allocate e.g.:
 - 6 boards starting at triad (5, 5)
 - a (2, 2) triad machine starting at triad (1, 1)
 
It is *not* necessary to allocate ranges that start partway through one triad and/or end partway through another (so the allocation is either one specific board, or a number of triads starting at a specific triad).

**Comment by dkfellows** [comment]
As long as you're OK with waiting a potentially long time for the allocation to go through, this should be reasonably easy. Needs a few changes in the model classes, and an enhanced query in the allocator core, but I believe it has _no_ database changes required.
