### ISSUE TITLE
Update to log4j-slf4j2-impl

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/JavaSpiNNaker#595]
Change here to make compatible again:
https://github.com/SpiNNakerManchester/JavaSpiNNaker/blob/6f9bbf25c3e541042cbf1b79e57058141924b981/pom.xml#L149

**Comment by dkfellows** [comment]
https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-slf4j2-impl
