### ISSUE TITLE
Undefined value for bare column sql group by

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/JavaSpiNNaker#693]
In some of the queries of the allocator a "group by" clause is used with "bare columns" (see https://www.sqlite.org/lang_select.html section 2.5).  This will lead to potentially incorrect results when e.g. selecting a rectangle starting at a specified coordinate or finding all possible rectangles including those with wrap arounds.

**Comment by rowleya** [comment]
As an example, take a 12 board system.  It should be possible to query for a 2x1 triad rectangle starting at board with triad coordinates 1, 1, 0, even if that isn't really a valid allocation.

**Comment by dkfellows** [comment]
Potential issue locations:
* `SQLQueries#GET_MACHINE_REPORTS`
  https://github.com/SpiNNakerManchester/JavaSpiNNaker/blob/550dfd865cf7b6187b89a3bc58f38b892c0e6717/SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/SQLQueries.java#L572
* queries/find_rectangle.sql
   https://github.com/SpiNNakerManchester/JavaSpiNNaker/blob/550dfd865cf7b6187b89a3bc58f38b892c0e6717/SpiNNaker-allocserv/src/main/resources/queries/find_rectangle.sql#L46
* queries/find_rectangle_at.sql
  https://github.com/SpiNNakerManchester/JavaSpiNNaker/blob/550dfd865cf7b6187b89a3bc58f38b892c0e6717/SpiNNaker-allocserv/src/main/resources/queries/find_rectangle_at.sql#L46
* queries/get_reported_boards.sql
  https://github.com/SpiNNakerManchester/JavaSpiNNaker/blob/550dfd865cf7b6187b89a3bc58f38b892c0e6717/SpiNNaker-allocserv/src/main/resources/queries/get_reported_boards.sql#L29
