### ISSUE TITLE
Remove code that can not be released under Apache 2.0

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/JavaSpiNNaker#711]
We plan to do the next release (soon we hope) under the Apache 2.0 license
See https://www.apache.org/licenses/LICENSE-2.0

The Apache 2.0 license is more permissive then the current GPL version 3 license.

Please remove any of your contributions you do not agree can be released under Apache 2.0

Or at least add a comment on this issue.

Otherwise we will assume agreement of all contributors.

**Comment by dkfellows** [comment]
All contributors to this repository were either UoM employees at the time (and so not eligible to object) or are @dependabot, which hasn't made any contribution that could be legally judged to be substantive.
