### ISSUE TITLE
equals printlns

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#73]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
============================
calling equals on a chip would result in lots of terminal output

What do you see that is wrong?
the terminal output. 

What do you think it should do instead?
not have terminal output

What version of our software are you using?
master
-------------------------------------------

**Comment by alan-stokes** [comment]
router.java has same issue

**Comment by Christian-B** [comment]
https://github.com/SpiNNakerManchester/JavaSpiNNaker/pull/97
