### ISSUE TITLE
surplus code

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#74]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
============================
surplus code resulting from 
reserveASystemProcessor
as the code in python that this was based off should have been removed when we moved the reinjecotr into the graph.

What do you see that is wrong?
that it exists

What do you think it should do instead?
not exist

What version of our software are you using?
master
-------------------------------------------

**Comment by Christian-B** [comment]
https://github.com/SpiNNakerManchester/JavaSpiNNaker/pull/97
