### ISSUE TITLE
Spalloc Job is not described in terms of chip width and height

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/JavaSpiNNaker#743]
The Spalloc job size for the compat service should return the size in terms of the width and height of the job in chips.  I believe this requires knowledge of the wrap-arounds of the machine, which is also not provided.

**Comment by dkfellows** [comment]
Shouldn't need knowledge of wraparounds; that's only required when going between global coordinates and job coordinates (any actual wraparounds that matter are for the concrete machine discovery process to find out).
