### ISSUE TITLE
ChipInformation seems redundant

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#75]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
the class ChipInformation.java in machine does not get used at all. 
What should use it (chipInfo in comms) does not use it. 
============================

What do you see that is wrong?
either redundant code, or incorrect instantiation of a class

What do you think it should do instead?
either move chipInformation or make chipInfo implement it

What version of our software are you using?
master
-------------------------------------------

**Comment by Christian-B** [comment]
can be removed as far I am am concerned

**Comment by dkfellows** [comment]
I think this was a class from the comms model that you thought was needed at one point and then discovered you didn't need.

**Comment by Christian-B** [comment]
https://github.com/SpiNNakerManchester/JavaSpiNNaker/pull/97
