### ISSUE TITLE
CoreSubsetsFailedChipsTuple i think is redudnant when system monitors are removed

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#76]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
surplus code
============================

What do you see that is wrong?
CoreSubsetsFailedChipsTuple  is only used by reserveSystemProcessors. which preivous issue states is legacy code

What do you think it should do instead?
go bye bye

What version of our software are you using?
master
-------------------------------------------

**Comment by Christian-B** [comment]
https://github.com/SpiNNakerManchester/JavaSpiNNaker/pull/97
