### ISSUE TITLE
none named magic numebrs

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#77]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
link.java hash code has magic numbers in it
============================

What do you see that is wrong?
they not named. I know this isnt major, but ya use named magic in tag.java hashcode, so keeping consistency, the link should have them named.

What do you think it should do instead?
name them

What version of our software are you using?
master
-------------------------------------------

**Comment by alan-stokes** [comment]
also MachineDimenions.java hashCode

**Comment by alan-stokes** [comment]
Processor.java

**Comment by Christian-B** [comment]
hashcode methods are excempt from the magic number rule.

As defined in 
https://github.com/SpiNNakerManchester/JavaSpiNNaker/blob/master/src/support/checkstyle/style.xml

		<module name="MagicNumber">
			<property name="ignoreHashCodeMethod" value="true" />
		</module>

**Comment by alan-stokes** [comment]
lol, then why did ya name them for one of the classes? consistency

**Comment by Christian-B** [comment]
We did not know we could turn it off when we did that.

Not worth changing back.

**Comment by alan-stokes** [comment]
hum bug.
