### ISSUE TITLE
Machine.java totalAvailableUserCores1, totalAvailableUserCores2

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#79]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
redundant code
============================

What do you see that is wrong?
    * @deprecated
     *      This method is purely to demonstrate/test the usage of
     *      stream so can be remove at any moment,
     */

What do you think it should do instead?
go bye bye

What version of our software are you using?
master
-------------------------------------------

**Comment by Christian-B** [comment]
https://github.com/SpiNNakerManchester/JavaSpiNNaker/pull/97
