### ISSUE TITLE
comment in wrong place

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#81]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
machineDefaults.java line 95
needs to move 1 space inwards
============================

What do you see that is wrong?
wrong location

What do you think it should do instead?
move 1 space inwards

What version of our software are you using?
master
-------------------------------------------

**Comment by alan-stokes** [comment]
also machine.java line 312

**Comment by Christian-B** [comment]
https://github.com/SpiNNakerManchester/JavaSpiNNaker/pull/97
