### ISSUE TITLE
commented out code

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#82]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
machineDefaults.java lines 164 to 183 should be deleted
============================

What do you see that is wrong?
legacy code

What do you think it should do instead?
go bye bye

What version of our software are you using?
master
-------------------------------------------

**Comment by alan-stokes** [comment]
triad geo lines 326 to 329

**Comment by alan-stokes** [comment]
virtualMachine line 99

**Comment by alan-stokes** [comment]
vertex lines 60 to 88

**Comment by Christian-B** [comment]
Done all except vertex as I haven't decided if we need those yes or no.

https://github.com/SpiNNakerManchester/JavaSpiNNaker/pull/97
