### ISSUE TITLE
@author 

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#84]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
loads of @author spread over all the java. Example is NeighbourIterator
============================

What do you see that is wrong?
given we have github tracking this, and the likelyhood of this going out of date, id propose removing them

What do you think it should do instead?
go bye bye

What version of our software are you using?
master
-------------------------------------------

**Comment by alan-stokes** [comment]
router.java

**Comment by alan-stokes** [comment]
triadGeo.java

**Comment by alan-stokes** [comment]
virtualMachine.java

**Comment by alan-stokes** [comment]
vertex.java

**Comment by alan-stokes** [comment]
dataReceiverRunner.java

**Comment by alan-stokes** [comment]
DataOut is in 2 places. lines 44, 45 and 52

**Comment by alan-stokes** [comment]
OperationMapper line 38

**Comment by alan-stokes** [comment]
Operation line 33

**Comment by alan-stokes** [comment]
memRegionCollector line 38

**Comment by alan-stokes** [comment]
functions.java line 53

**Comment by alan-stokes** [comment]
host execute data spec line 43

**Comment by Christian-B** [comment]
We disagree!
