### ISSUE TITLE
public vs private

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#88]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
SpiNNakerTriadGeometry.java has 2 public variables that are not used anywhere outside of the class. 
    /** Height of a triad in chips. */
    public final int triadHeight;
    /** Width of a triad in chips. */
    public final int triadWidth;
============================

What do you see that is wrong?

    /** Height of a triad in chips. */
    public final int triadHeight;
    /** Width of a triad in chips. */
    public final int triadWidth;

What do you think it should do instead?

    /** Height of a triad in chips. */
    private final int triadHeight;
    /** Width of a triad in chips. */
    private final int triadWidth;

What version of our software are you using?
master
-------------------------------------------

**Comment by Christian-B** [comment]
final imutable can be public

**Comment by alan-stokes** [comment]
but theres no need in this case. nothing would use them outside this classes internals

**Comment by Christian-B** [comment]
no need != bad

**Comment by alan-stokes** [comment]
lots of little no need != bad can accum to == bad. lol.
