### ISSUE TITLE
no docs

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#91]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
no docs on triad geo on line 284
============================

What do you see that is wrong?
missing doc

What do you think it should do instead?
fill in doc. no idea what singleBoardForEach(action) does

What version of our software are you using?
master
-------------------------------------------

**Comment by Christian-B** [comment]
https://github.com/SpiNNakerManchester/JavaSpiNNaker/pull/97
