### ISSUE TITLE
i think this is wrong. but im not sure

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#92]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
vertex.java I think its pulling something that is unexpected. it might be correct (being its a protected variable, but id rather it be private and explicit than implicit).
============================

What do you see that is wrong?
    int[] getRecordedRegionIds() {
        return recordedRegionIds;
    }

What do you think it should do instead?

    int[] getRecordedRegionIds() {
        return this.recordedRegionIds;
    }

I think you need to add private to the variable declairations as well. 

What version of our software are you using?
master
-------------------------------------------

**Comment by Christian-B** [comment]
Agreed it is mutable.  
https://github.com/SpiNNakerManchester/JavaSpiNNaker/pull/97
