### ISSUE TITLE
try without catch

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#93]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
HostDataRerceiver.java lines 200 to 203. has no catch
============================

What do you see that is wrong?
has no catch

What do you think it should do instead?
have a catch of some level, even its just a overall exception

What version of our software are you using?
master
-------------------------------------------

**Comment by Christian-B** [comment]
https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

**Comment by alan-stokes** [comment]
fair enough. *I bow to your superiority here*

**Comment by Christian-B** [comment]
Where is that print button!

**Comment by dkfellows** [comment]
Chimp beats puppy.

**Comment by alan-stokes** [comment]
lol, chimp beats sick puppy. chimp beats puppy when chimp is right.
