### ISSUE TITLE
dse reload functionality using a constant that is not consistent between machines

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/JavaSpiNNaker#95]
_Remember: the better you describe your issue, the easier it is for us to help you._

What is the problem you see?
private static final int DEFAULT_SDRAM_BYTES = 117 * 1024 * 1024;
============================

What do you see that is wrong?
this constant is possible to not be a constant and should be read from the machine chip in question

What do you think it should do instead?
public void reload(HasCoreLocation core, LocationInfo info, File dataSpec) should also take the machine, and read the chip linked to coreLocation and get the sdram from the specific chip. 

What version of our software are you using?
master
-------------------------------------------

**Comment by alan-stokes** [comment]
and here
public void reload(HasCoreLocation core, File dataSpec)

**Comment by Christian-B** [comment]
These methods have neither a Chip nor Machine object from which to get this info.

**Comment by Christian-B** [comment]
The constant however if used should be in MachineDefaults.

**Comment by dkfellows** [comment]
I'm more likely to kill that method entirely sometime in the future.

**Comment by alan-stokes** [comment]
up to you. i think the changes are relatively easy. and reload i think reflects the run, set, run mode. so it might be worth having the support in java for parallel support. but up to ya

**Comment by dkfellows** [comment]
* The methods concerned are gone, so fixing them is impossible.
* The constant is in `uk.ac.manchester.spinnaker.machine.MachineDefaults`.
